apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp-2
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ["sh", "-c", "echo Welcome to Kubernetes! && sleep 3600"]
